cookie:
  expiry_days: 30
  key: sympflaura_secret_key_123
  name: sympflaura_auth_cookie
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      first_name: John
      last_name: Smith
      logged_in: false
      password: $2b$12$LZNzmnSBUE2TNkhar.eJG.BSvfS1hExKWdIR2YtT6TywVaZcRb7ii
      roles:
      - admin
      - editor
      - viewer
    User:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      first_name: User
      last_name: (Demo)
      logged_in: false
      password: $2b$12$Hxf/P.A0YyL64Q.7l9GBSudkymmmvBTsNa2CWa0XnsKV0.Cq7XrLK
      roles:
      - viewer
